/**
 * Command Aliases Configuration
 * Maps shortened command names to their full command names
 * Ultra-organized • 1000+ aliases • Optimized lookups
 */

// ─── Constants ────────────────────────────────────────────────────────────────

const MAX_ALIAS_LENGTH = 32;

// ─── Command Aliases ──────────────────────────────────────────────────────────

export const commandAliases = {

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Economy ────────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  bal: 'balance',
  bank: 'balance',
  cash: 'balance',
  money: 'balance',
  wallet: 'balance',
  dep: 'deposit',
  deposit: 'deposit',
  with: 'withdraw',
  withdrawal: 'withdraw',
  job: 'work',
  work: 'work',
  claim: 'daily',
  dailies: 'daily',
  daily: 'daily',
  bet: 'gamble',
  dicegame: 'gamble',
  gamble: 'gamble',
  slots: 'gamble',
  heist: 'rob',
  rob: 'rob',
  steal: 'rob',
  crime: 'crime',
  illegal: 'crime',
  give: 'pay',
  pay: 'pay',
  send: 'pay',
  share: 'pay',
  transfer: 'pay',
  beg: 'beg',
  plead: 'beg',
  find: 'search',
  lookup: 'search',
  scout: 'search',
  search: 'search',
  hunt: 'hunt',
  fish: 'fish',
  mine: 'mine',
  chop: 'chop',
  woodcutting: 'chop',
  sell: 'sell',
  buyitem: 'buyitem',
  consume: 'use',
  use: 'use',
  lb: 'leaderboard',
  leaderboard: 'leaderboard',
  levels: 'leaderboard',
  lvllb: 'leaderboard',
  richest: 'leaderboard',
  top: 'leaderboard',
  xplb: 'leaderboard',
  networth: 'networth',
  nw: 'networth',
  profile: 'profile',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Core / System ──────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  latency: 'ping',
  ping: 'ping',
  pong: 'ping',
  about: 'help',
  cmds: 'help',
  commands: 'help',
  docs: 'help',
  h: 'help',
  help: 'help',
  info: 'help',
  manual: 'help',
  addbot: 'invite',
  invite: 'invite',
  server: 'support',
  support: 'support',
  donate: 'donate',
  patreon: 'premium',
  premium: 'premium',
  upvote: 'vote',
  botinfo: 'stats',
  stats: 'stats',
  status: 'status',
  uptime: 'uptime',
  shard: 'shard',
  pingall: 'pingall',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Moderation ─────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  ban: 'ban',
  banuser: 'ban',
  ub: 'unban',
  unban: 'unban',
  k: 'kick',
  kick: 'kick',
  removeuser: 'kick',
  mute: 'timeout',
  tempmute: 'timeout',
  timeout: 'timeout',
  to: 'timeout',
  unmute: 'untimeout',
  untimeout: 'untimeout',
  uto: 'untimeout',
  strike: 'warn',
  warn: 'warn',
  rmwarn: 'unwarn',
  unwarn: 'unwarn',
  strikes: 'warnings',
  warnings: 'warnings',
  warns: 'warnings',
  clean: 'purge',
  clear: 'purge',
  clearchat: 'purge',
  del: 'purge',
  delete: 'purge',
  prune: 'purge',
  purge: 'purge',
  slow: 'slowmode',
  slowmode: 'slowmode',
  sm: 'slowmode',
  lock: 'lock',
  unlock: 'unlock',
  hide: 'hide',
  unhide: 'unhide',
  announce: 'announce',
  broadcast: 'announce',
  echo: 'say',
  say: 'say',
  embed: 'embed',
  addrole: 'role',
  giverole: 'role',
  role: 'role',
  removerole: 'takerole',
  takerole: 'takerole',
  nick: 'nickname',
  nickname: 'nickname',
  setnick: 'nickname',
  cases: 'modlog',
  modlog: 'modlog',
  editreason: 'reason',
  reason: 'reason',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Auto-Moderation ────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  \'anti-raid\': 'automoderation',
  \'anti-spam\': 'automoderation',
  \'auto-mod\': 'automoderation',
  am: 'automoderation',
  amconfig: 'automoderation',
  amsetup: 'automoderation',
  antighost: 'automoderation',
  antihoist: 'automoderation',
  antiphish: 'automoderation',
  antiraid: 'automoderation',
  antiscam: 'automoderation',
  antispam: 'automoderation',
  automod: 'automoderation',
  automodconfig: 'automoderation',
  badwords: 'automoderation',
  blacklistwords: 'automoderation',
  caps: 'automoderation',
  dehoist: 'automoderation',
  filter: 'automoderation',
  links: 'automoderation',
  mentions: 'automoderation',
  profanity: 'automoderation',
  scam: 'automoderation',
  selfbot: 'automoderation',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Leveling & XP ──────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  card: 'rank',
  exp: 'rank',
  level: 'rank',
  lvl: 'rank',
  rank: 'rank',
  xp: 'rank',
  resetlevel: 'resetxp',
  resetxp: 'resetxp',
  addxp: 'addxp',
  givexp: 'addxp',
  removexp: 'removexp',
  takexp: 'removexp',
  boost: 'xpmultiplier',
  doublexp: 'xpmultiplier',
  xpmult: 'xpmultiplier',
  xpmultiplier: 'xpmultiplier',
  lvlrole: 'rolelevel',
  rolelevel: 'rolelevel',
  stackroles: 'stackroles',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Shop & Inventory ───────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  catalog: 'shop',
  market: 'shop',
  shop: 'shop',
  store: 'shop',
  buy: 'buy',
  purchase: 'buy',
  backpack: 'inventory',
  bag: 'inventory',
  inv: 'inventory',
  inventory: 'inventory',
  items: 'inventory',
  equip: 'equip',
  wear: 'equip',
  useitem: 'useitem',
  sellitem: 'sellitem',
  trade: 'trade',
  gift: 'gift',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Utility & Tools ────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  memberinfo: 'userinfo',
  ui: 'userinfo',
  user: 'userinfo',
  userinfo: 'userinfo',
  whois: 'userinfo',
  avatar: 'avatar',
  icon: 'avatar',
  pfp: 'avatar',
  banner: 'banner',
  gi: 'serverinfo',
  guildinfo: 'serverinfo',
  serverinfo: 'serverinfo',
  si: 'serverinfo',
  guildicon: 'servericon',
  servericon: 'servericon',
  emoji: 'emojis',
  emojis: 'emojis',
  emotes: 'emojis',
  rolelist: 'roles',
  roles: 'roles',
  channellist: 'channels',
  channels: 'channels',
  memberlist: 'members',
  members: 'members',
  invitelist: 'invites',
  invites: 'invites',
  boosters: 'boosters',
  boosts: 'boosters',
  calc: 'calculate',
  calculate: 'calculate',
  calculator: 'calculate',
  math: 'calculate',
  forecast: 'weather',
  w: 'weather',
  weather: 'weather',
  time: 'time',
  timezone: 'time',
  tz: 'time',
  tr: 'translate',
  translate: 'translate',
  remind: 'remind',
  reminder: 'remind',
  remindme: 'remind',
  countdown: 'timer',
  timer: 'timer',
  poll: 'poll',
  strawpoll: 'poll',
  vote: 'poll',
  quote: 'quote',
  addemoji: 'stealemoji',
  stealemoji: 'stealemoji',
  bigemoji: 'enlarge',
  enlarge: 'enlarge',
  snipe: 'snipe',
  editsnipe: 'esnipe',
  esnipe: 'esnipe',
  afk: 'afk',
  away: 'afk',
  agenda: 'note',
  annotation: 'note',
  brainstorm: 'note',
  clipboard: 'note',
  commentary: 'note',
  draft: 'note',
  jot: 'note',
  jotting: 'note',
  memo: 'note',
  memorandum: 'note',
  minutes: 'note',
  note: 'note',
  notepad: 'note',
  notes: 'note',
  observation: 'note',
  outline: 'note',
  postit: 'note',
  remark: 'note',
  rough: 'note',
  scratchpad: 'note',
  scribble: 'note',
  sketch: 'note',
  thought: 'note',
  sticky: 'sticky',
  stickymsg: 'sticky',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Birthday ───────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  b: 'birthday',
  bd: 'birthday',
  bday: 'birthday',
  birthday: 'birthday',
  setbirthday: 'birthday',
  nextbd: 'nextbirthday',
  nextbday: 'nextbirthday',
  birthdays: 'birthdays',
  bdlb: 'birthdayleaderboard',
  birthdaylb: 'birthdayleaderboard',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Fun & Games ────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  coin: 'flip',
  coinflip: 'flip',
  flip: 'flip',
  toss: 'flip',
  d20: 'roll',
  dice: 'roll',
  roll: 'roll',
  rolldice: 'roll',
  rockpaperscissors: 'rps',
  rps: 'rps',
  battle: 'fight',
  duel: 'fight',
  fight: 'fight',
  pvp: 'fight',
  cuddle: 'hug',
  hug: 'hug',
  kiss: 'kiss',
  slap: 'slap',
  punch: 'punch',
  kill: 'kill',
  murder: 'kill',
  love: 'ship',
  match: 'ship',
  ship: 'ship',
  rate: 'rate',
  waifu: 'waifu',
  husbando: 'husbando',
  marry: 'marry',
  divorce: 'divorce',
  pet: 'pet',
  feed: 'feed',
  tickle: 'tickle',
  poke: 'poke',
  hf: 'highfive',
  highfive: 'highfive',
  wave: 'wave',
  wink: 'wink',
  dance: 'dance',
  cry: 'cry',
  laugh: 'laugh',
  lmao: 'laugh',
  meme: 'meme',
  reddit: 'meme',
  dadjoke: 'joke',
  joke: 'joke',
  burn: 'roast',
  roast: 'roast',
  \'8ball\': '8ball',
  ask: '8ball',
  fortune: '8ball',
  choose: 'choose',
  pick: 'choose',
  random: 'random',
  rng: 'random',
  question: 'trivia',
  quiz: 'trivia',
  trivia: 'trivia',
  hangman: 'hangman',
  guess: 'wordle',
  wordle: 'wordle',
  \'21\': 'blackjack',
  bj: 'blackjack',
  blackjack: 'blackjack',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Giveaway ───────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  gbegin: 'gcreate',
  gcreate: 'gcreate',
  gstart: 'gcreate',
  gend: 'gend',
  gfinish: 'gend',
  gstop: 'gend',
  gdelete: 'gdelete',
  gremove: 'gdelete',
  greroll: 'greroll',
  groll: 'greroll',
  giveaways: 'glist',
  glist: 'glist',
  gentries: 'gentries',
  gwinners: 'gwinners',
  gedit: 'gedit',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Ticket System ──────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  create: 'ticket',
  new: 'ticket',
  open: 'ticket',
  t: 'ticket',
  ticket: 'ticket',
  close: 'close',
  resolve: 'close',
  add: 'add',
  deq: 'remove',
  remove: 'remove',
  rm: 'remove',
  ticketpanel: 'ticketpanel',
  tpanel: 'ticketpanel',
  ticketsetup: 'ticketsetup',
  tsetup: 'ticketsetup',
  transcript: 'transcript',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Verification ───────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  ver: 'verify',
  verify: 'verify',
  vadmin: 'verification',
  verification: 'verification',
  verifysetup: 'verification',
  autoverify: 'autoverify',
  av: 'autoverify',
  verifyrole: 'verifyrole',
  captcha: 'captcha',
  verifylog: 'verifylog',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Welcome & Goodbye ──────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  welcome: 'welcome',
  welcomemsg: 'welcome',
  welcomecard: 'welcomeimg',
  welcomeimg: 'welcomeimg',
  goodbye: 'goodbye',
  leavemsg: 'goodbye',
  goodbyecard: 'goodbyecard',
  autorole: 'autorole',
  defaultrole: 'autorole',
  joinrole: 'autorole',
  welcometest: 'welcometest',
  goodbyetest: 'goodbyetest',
  welcomelb: 'welcomelb',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Music ──────────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  current: 'nowplaying',
  now: 'nowplaying',
  np: 'nowplaying',
  playing: 'nowplaying',
  song: 'nowplaying',
  p: 'play',
  play: 'play',
  sc: 'play',
  soundcloud: 'play',
  spotify: 'play',
  youtube: 'play',
  yt: 'play',
  forceskip: 'skip',
  fs: 'skip',
  next: 'skip',
  s: 'skip',
  skip: 'skip',
  list: 'queue',
  q: 'queue',
  queue: 'queue',
  songs: 'queue',
  pause: 'pause',
  continue: 'resume',
  r: 'resume',
  resume: 'resume',
  unpause: 'resume',
  end: 'stop',
  leave: 'stop',
  stop: 'stop',
  dc: 'disconnect',
  disconnect: 'disconnect',
  quit: 'disconnect',
  v: 'volume',
  vol: 'volume',
  volume: 'volume',
  l: 'loop',
  loop: 'loop',
  repeat: 'loop',
  randomize: 'shuffle',
  shuff: 'shuffle',
  shuffle: 'shuffle',
  lyric: 'lyrics',
  lyrics: 'lyrics',
  words: 'lyrics',
  find: 'search',
  lookup: 'search',
  scout: 'search',
  search: 'search',
  deq: 'remove',
  remove: 'remove',
  rm: 'remove',
  jump: 'move',
  move: 'move',
  mv: 'move',
  skipto: 'skipto',
  playnext: 'playnext',
  pn: 'playnext',
  playskip: 'playskip',
  ps: 'playskip',
  bassboost: 'bassboost',
  bb: 'bassboost',
  nc: 'nightcore',
  nightcore: 'nightcore',
  vaporwave: 'vaporwave',
  vw: 'vaporwave',
  speed: 'speed',
  tempo: 'speed',
  pitch: 'pitch',
  goto: 'seek',
  seek: 'seek',
  rewind: 'rewind',
  rw: 'rewind',
  ff: 'forward',
  forward: 'forward',
  savequeue: 'savequeue',
  loadqueue: 'loadqueue',
  pl: 'playlist',
  playlist: 'playlist',
  autoplay: 'autoplay',
  related: 'autoplay',
  radio: 'radio',
  station: 'radio',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Server Stats / Logging ─────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  serverstats: 'serverstats',
  ss: 'serverstats',
  sstats: 'serverstats',
  statschannel: 'serverstats',
  mc: 'membercount',
  membercount: 'membercount',
  bc: 'boostcount',
  boostcount: 'boostcount',
  logsetup: 'logsetup',
  auditlog: 'auditlog',
  messagelog: 'messagelog',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Reaction Roles ─────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  reactionrole: 'reactroles',
  reactionroles: 'reactroles',
  rr: 'reactroles',
  rrpanel: 'rrpanel',
  rrsetup: 'rrsetup',
  rradd: 'rradd',
  rrremove: 'rrremove',
  rrlist: 'rrlist',
  rredit: 'rredit',
  rrclear: 'rrclear',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Join-To-Create / Voice ─────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  jointocreate: 'jointocreate',
  jtc: 'jointocreate',
  tempvc: 'jointocreate',
  vctemp: 'jointocreate',
  jtcsetup: 'jtcsetup',
  jtcconfig: 'jtcconfig',
  vcclaim: 'voiceclaim',
  voiceclaim: 'voiceclaim',
  voicetransfer: 'voicetransfer',
  vclock: 'vclock',
  vclimit: 'vclimit',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Suggestions ────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  idea: 'suggest',
  suggest: 'suggest',
  suggestion: 'suggest',
  suggestsetup: 'suggestsetup',
  suggestchannel: 'suggestchannel',
  suggestapprove: 'suggestapprove',
  suggestdeny: 'suggestdeny',
  suggestconsider: 'suggestconsider',
  suggestimplement: 'suggestimplement',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Starboard ──────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  sb: 'starboard',
  star: 'starboard',
  starboard: 'starboard',
  starsetup: 'starsetup',
  staremoji: 'staremoji',
  starthreshold: 'starthreshold',
  starlb: 'starlb',
  starleaderboard: 'starlb',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Counting / Leveling Games ──────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  count: 'counting',
  counting: 'counting',
  countsetup: 'countsetup',
  countinglb: 'countlb',
  countlb: 'countlb',
  gn: 'guessnumber',
  guessnumber: 'guessnumber',
  numbergame: 'guessnumber',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Logging & Reports ──────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  report: 'report',
  reports: 'report',
  reportsetup: 'reportsetup',
  ticketreport: 'ticketreport',
  feedback: 'feedback',
  bug: 'bugreport',
  bugreport: 'bugreport',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Custom Commands / Tags ─────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  tag: 'tag',
  cc: 'customcommand',
  customcommand: 'customcommand',
  addtag: 'addtag',
  edittag: 'edittag',
  deletetag: 'deletetag',
  taglist: 'taglist',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Reminders & Timers ─────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  remind: 'remind',
  reminder: 'remind',
  remindme: 'remind',
  remindall: 'remindall',
  countdown: 'timer',
  timer: 'timer',
  alarm: 'alarm',
  remindlist: 'remindlist',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Todo ───────────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  checklist: 'todo',
  task: 'todo',
  tasks: 'todo',
  todo: 'todo',
  addtask: 'todoadd',
  todoadd: 'todoadd',
  todoremove: 'todoremove',
  todolist: 'todolist',
  todoclear: 'todoclear',
  tododone: 'tododone',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Social / Profile ───────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  rep: 'reputation',
  reputation: 'reputation',
  respect: 'reputation',
  repgive: 'repgive',
  repboard: 'repboard',
  profile: 'profile',
  bio: 'bio',
  setbio: 'bio',
  background: 'background',
  bg: 'background',
  badge: 'badge',
  title: 'title',
  customstatus: 'customstatus',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Admin / Owner ──────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  eval: 'eval',
  execute: 'eval',
  exec: 'exec',
  shell: 'exec',
  reload: 'reload',
  reboot: 'restart',
  restart: 'restart',
  shutdown: 'shutdown',
  maintenance: 'maintenance',
  prefix: 'setprefix',
  setprefix: 'setprefix',
  blacklistuser: 'blacklistuser',
  blacklistguild: 'blacklistguild',
  whitelist: 'whitelist',
  owner: 'owner',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Image / Manipulation ───────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  trigger: 'trigger',
  triggered: 'trigger',
  blur: 'blur',
  pixelate: 'pixelate',
  invert: 'invert',
  grayscale: 'greyscale',
  greyscale: 'greyscale',
  wanted: 'wanted',
  jail: 'jail',
  rip: 'rip',
  trash: 'trash',
  beautiful: 'beautiful',
  facepalm: 'facepalm',
  affect: 'affect',
  bobross: 'bobross',
  deleteimg: 'deleteimg',
  hitler: 'hitler',
  kissimg: 'kissimg',
  slapimg: 'slapimg',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Anime / Manga ──────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  anime: 'anime',
  manga: 'manga',
  char: 'character',
  character: 'character',
  anilist: 'anilist',
  mal: 'mal',
  myanimelist: 'mal',
  animequote: 'animequote',
  waifupic: 'waifupic',
  neko: 'neko',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Minecraft / Gaming ─────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  mcserver: 'mcserver',
  minecraft: 'mcserver',
  mcskin: 'mcskin',
  mcuser: 'mcuser',
  steam: 'steam',
  fn: 'fortnite',
  fortnite: 'fortnite',
  apex: 'apex',
  val: 'valorant',
  valorant: 'valorant',
  league: 'lol',
  lol: 'lol',
  osu: 'osu',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── NSFW / 18+ ─────────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  lewd: 'nsfw',
  nsfw: 'nsfw',
  r34: 'rule34',
  rule34: 'rule34',
  gelbooru: 'gelbooru',
  danbooru: 'danbooru',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Misc / Extra ───────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  color: 'color',
  colour: 'color',
  hex: 'color',
  rgb: 'rgb',
  passgen: 'password',
  password: 'password',
  shorten: 'shorten',
  url: 'shorten',
  base64: 'base64',
  encode: 'encode',
  decode: 'decode',
  binary: 'binary',
  morse: 'morse',
  ascii: 'ascii',
  figlet: 'figlet',
  textart: 'figlet',
  firstmessage: 'firstmsg',
  firstmsg: 'firstmsg',
  permissions: 'permissions',
  perms: 'permissions',
  botperms: 'botperms',
  invinfo: 'inviteinfo',
  inviteinfo: 'inviteinfo',
  vanity: 'vanity',
  splash: 'splash',
  discover: 'discover',
  bump: 'bump',
  review: 'review',
  serverreview: 'review',
  serverlist: 'serverlist',
  partners: 'partners',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── AI & Chatbot ───────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  agent: 'ai',
  artificialintelligence: 'ai',
  assistant: 'ai',
  chatgpt: 'ai',
  classifier: 'ai',
  claude: 'ai',
  cognitive: 'ai',
  companion: 'ai',
  copilot: 'ai',
  dalle: 'ai',
  deep learning: 'ai',
  diffusion: 'ai',
  embedding: 'ai',
  finetune: 'ai',
  gemini: 'ai',
  generator: 'ai',
  gpt: 'ai',
  inference: 'ai',
  llm: 'ai',
  machinelearning: 'ai',
  midjourney: 'ai',
  ml: 'ai',
  naturallanguage: 'ai',
  neuralnetwork: 'ai',
  nlp: 'ai',
  prompt: 'ai',
  promptengineering: 'ai',
  sentiment: 'ai',
  stable: 'ai',
  token: 'ai',
  tokenizer: 'ai',
   proclaim: 'chat',
  alert: 'chat',
  answer: 'chat',
  articulate: 'chat',
  comment: 'chat',
  communicate: 'chat',
  conversation: 'chat',
  converse: 'chat',
  correspond: 'chat',
  declare: 'chat',
  dialogue: 'chat',
  discuss: 'chat',
  dm: 'chat',
  engage: 'chat',
  exchange: 'chat',
  express: 'chat',
  interact: 'chat',
  mention: 'chat',
  message: 'chat',
  notify: 'chat',
  pm: 'chat',
  reply: 'chat',
  respond: 'chat',
  state: 'chat',
  talk: 'chat',
  thread: 'chat',
  verbalize: 'chat',
  adviseai: 'askai',
  analyzeai: 'askai',
  brainstormai: 'askai',
  buildai: 'askai',
  coachai: 'askai',
  codeai: 'askai',
  consultai: 'askai',
  createai: 'askai',
  designai: 'askai',
  drawai: 'askai',
  dreamai: 'askai',
  explainai: 'askai',
  generateai: 'askai',
  guideai: 'askai',
  helpai: 'askai',
  ideateai: 'askai',
  imagineai: 'askai',
  inquireai: 'askai',
  mentorai: 'askai',
  planai: 'askai',
  queryai: 'askai',
  questionai: 'askai',
  recommendai: 'askai',
  strategizeai: 'askai',
  suggestai: 'askai',
  summarizeai: 'askai',
  supportai: 'askai',
  teachai: 'askai',
  translateai: 'askai',
  tutorai: 'askai',
  writeai: 'askai',
  3dai: 'imageai',
  aiimage: 'imageai',
  animateai: 'imageai',
  artimage: 'imageai',
  avatarai: 'imageai',
  bannerai: 'imageai',
  buildimage: 'imageai',
  conceptimage: 'imageai',
  createimage: 'imageai',
  draftimage: 'imageai',
  drawimage: 'imageai',
  dreamimage: 'imageai',
  generateimage: 'imageai',
  gifai: 'imageai',
  graphicai: 'imageai',
  illustrateimage: 'imageai',
  imagineimage: 'imageai',
  logoai: 'imageai',
  makeimage: 'imageai',
  memeai: 'imageai',
  paintimage: 'imageai',
  photoai: 'imageai',
  pictureai: 'imageai',
  renderimage: 'imageai',
  sketchimage: 'imageai',
  synthesizeimage: 'imageai',
  thumbnailai: 'imageai',
  videoai: 'imageai',
  visualizeimage: 'imageai',
  wallpaperai: 'imageai',
  abridge: 'summarize',
  abstract: 'summarize',
  boildown: 'summarize',
  brief: 'summarize',
  cliffnotes: 'summarize',
  compact: 'summarize',
  compress: 'summarize',
  condense: 'summarize',
  digest: 'summarize',
  distill: 'summarize',
  dumbdown: 'summarize',
  eli5: 'summarize',
  executivesummary: 'summarize',
  explainlikeimfive: 'summarize',
  extract: 'summarize',
  highlight: 'summarize',
  keypoints: 'summarize',
  minify: 'summarize',
  overview: 'summarize',
  recap: 'summarize',
  reduce: 'summarize',
  roundup: 'summarize',
  simplify: 'summarize',
  sparknotes: 'summarize',
  summary: 'summarize',
  synopsis: 'summarize',
  takeaways: 'summarize',
  tldr: 'summarize',
  truncate: 'summarize',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Crypto & Web3 ──────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  altcoin: 'crypto',
  avalanche: 'crypto',
  binance: 'crypto',
  bitcoin: 'crypto',
  blockchain: 'crypto',
  btc: 'crypto',
  cardano: 'crypto',
  cex: 'crypto',
  chainlink: 'crypto',
  coinbase: 'crypto',
  cryptocurrency: 'crypto',
  dao: 'crypto',
  defi: 'crypto',
  dex: 'crypto',
  eth: 'crypto',
  ethereum: 'crypto',
  kraken: 'crypto',
  ledger: 'crypto',
  memecoin: 'crypto',
  metamask: 'crypto',
  nft: 'crypto',
  polkadot: 'crypto',
  shitcoin: 'crypto',
  solana: 'crypto',
  stablecoin: 'crypto',
  trezor: 'crypto',
  trustwallet: 'crypto',
  web3: 'crypto',
  arbiscan: 'wallet',
  argent: 'wallet',
  block: 'wallet',
  blockexplorer: 'wallet',
  bscscan: 'wallet',
  cryptowallet: 'wallet',
  debank: 'wallet',
  digitalwallet: 'wallet',
  etherscan: 'wallet',
  explorer: 'wallet',
  gas: 'wallet',
  gwei: 'wallet',
  hash: 'wallet',
  nonce: 'wallet',
  optimistic: 'wallet',
  phantom: 'wallet',
  polygonscan: 'wallet',
  rainbow: 'wallet',
  snowtrace: 'wallet',
  transaction: 'wallet',
  tx: 'wallet',
  web3wallet: 'wallet',
  wei: 'wallet',
  zapper: 'wallet',
  zerion: 'wallet',
  appraisal: 'price',
  apr: 'price',
  apy: 'price',
  bid: 'price',
  candlestick: 'price',
  chart: 'price',
  consensus: 'price',
  cost: 'price',
  depth: 'price',
  estimate: 'price',
  farming: 'price',
  impermanentloss: 'price',
  liquidity: 'price',
  marketcap: 'price',
  mining: 'price',
  ohlc: 'price',
  orderbook: 'price',
  quotation: 'price',
  slippage: 'price',
  spread: 'price',
  staking: 'price',
  ticker: 'price',
  validation: 'price',
  valuation: 'price',
  value: 'price',
  worth: 'price',
  yield: 'price',
  area: 'chart',
  bar: 'chart',
  boxplot: 'chart',
  bubble: 'chart',
  candle: 'chart',
  diagram: 'chart',
  display: 'chart',
  donut: 'chart',
  figure: 'chart',
  flowchart: 'chart',
  funnel: 'chart',
  gantt: 'chart',
  gauge: 'chart',
  graph: 'chart',
  heatmap: 'chart',
  histogram: 'chart',
  illustration: 'chart',
  line: 'chart',
  mindmap: 'chart',
  pie: 'chart',
  plot: 'chart',
  radar: 'chart',
  representation: 'chart',
  sankey: 'chart',
  scatter: 'chart',
  sparkline: 'chart',
  timeline: 'chart',
  treemap: 'chart',
  violin: 'chart',
  visualization: 'chart',
  basefee: 'gas',
  blobfee: 'gas',
  blockchainfee: 'gas',
  canceltx: 'gas',
  cryptofee: 'gas',
  eip1559: 'gas',
  executionfee: 'gas',
  failedtx: 'gas',
  gasfee: 'gas',
  inclusionfee: 'gas',
  legacytx: 'gas',
  maxfee: 'gas',
  mempool: 'gas',
  minerfee: 'gas',
  networkfee: 'gas',
  pendingtx: 'gas',
  priorityfee: 'gas',
  rent: 'gas',
  replace: 'gas',
  revertedtx: 'gas',
  speedup: 'gas',
  storagefee: 'gas',
  stucktx: 'gas',
  tip: 'gas',
  transactionfee: 'gas',
  txpool: 'gas',
  type2tx: 'gas',
  validationfee: 'gas',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Productivity ───────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  agenda: 'note',
  annotation: 'note',
  brainstorm: 'note',
  clipboard: 'note',
  commentary: 'note',
  draft: 'note',
  jot: 'note',
  jotting: 'note',
  memo: 'note',
  memorandum: 'note',
  minutes: 'note',
  note: 'note',
  notepad: 'note',
  notes: 'note',
  observation: 'note',
  outline: 'note',
  postit: 'note',
  remark: 'note',
  rough: 'note',
  scratchpad: 'note',
  scribble: 'note',
  sketch: 'note',
  thought: 'note',
  archive: 'bookmark',
  buffer: 'bookmark',
  cache: 'bookmark',
  category: 'bookmark',
  collection: 'bookmark',
  favorite: 'bookmark',
  favourite: 'bookmark',
  flag: 'bookmark',
  folder: 'bookmark',
  hoard: 'bookmark',
  hold: 'bookmark',
  keep: 'bookmark',
  label: 'bookmark',
  maintain: 'bookmark',
  mark: 'bookmark',
  pin: 'bookmark',
  preserve: 'bookmark',
  readinglist: 'bookmark',
  reserve: 'bookmark',
  retain: 'bookmark',
  save: 'bookmark',
  stash: 'bookmark',
  stockpile: 'bookmark',
  watchlist: 'bookmark',
  appointment: 'reminder',
  beep: 'reminder',
  bell: 'reminder',
  buzz: 'reminder',
  call: 'reminder',
  chime: 'reminder',
  cue: 'reminder',
  deadline: 'reminder',
  duedate: 'reminder',
  event: 'reminder',
  hint: 'reminder',
  inform: 'reminder',
  jog: 'reminder',
  meeting: 'reminder',
  notice: 'reminder',
  nudge: 'reminder',
  prod: 'reminder',
  schedule: 'reminder',
  signal: 'reminder',
  tell: 'reminder',
  warning: 'reminder',
  absence: 'calendar',
  almanac: 'calendar',
  attendance: 'calendar',
  cal: 'calendar',
  datebook: 'calendar',
  daybook: 'calendar',
  diary: 'calendar',
  epoch: 'calendar',
  era: 'calendar',
  holiday: 'calendar',
  itinerary: 'calendar',
  journal: 'calendar',
  organizer: 'calendar',
  period: 'calendar',
  planner: 'calendar',
  program: 'calendar',
  quarter: 'calendar',
  sabbatical: 'calendar',
  season: 'calendar',
  semester: 'calendar',
  term: 'calendar',
  timesheet: 'calendar',
  timetable: 'calendar',
  vacation: 'calendar',
  week: 'calendar',
  weekday: 'calendar',
  weekend: 'calendar',
  automation: 'habit',
  blueprint: 'habit',
  ceremony: 'habit',
  convention: 'habit',
  custom: 'habit',
  discipline: 'habit',
  disposition: 'habit',
  framework: 'habit',
  habitude: 'habit',
  inclination: 'habit',
  macro: 'habit',
  observance: 'habit',
  penchant: 'habit',
  pipeline: 'habit',
  practice: 'habit',
  predilection: 'habit',
  procedure: 'habit',
  process: 'habit',
  proclivity: 'habit',
  protocol: 'habit',
  quirk: 'habit',
  regime: 'habit',
  regimen: 'habit',
  ritual: 'habit',
  routine: 'habit',
  shortcut: 'habit',
  template: 'habit',
  tendency: 'habit',
  tradition: 'habit',
  workflow: 'habit',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Knowledge & Learning ───────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  academia: 'wiki',
  academy: 'wiki',
  anthology: 'wiki',
  college: 'wiki',
  compendium: 'wiki',
  corpus: 'wiki',
  database: 'wiki',
  directory: 'wiki',
  education: 'wiki',
  encyclopedia: 'wiki',
  guide: 'wiki',
  handbook: 'wiki',
  index: 'wiki',
  institute: 'wiki',
  knowledge: 'wiki',
  learning: 'wiki',
  library: 'wiki',
  primer: 'wiki',
  reference: 'wiki',
  repository: 'wiki',
  research: 'wiki',
  scholarship: 'wiki',
  school: 'wiki',
  study: 'wiki',
  textbook: 'wiki',
  university: 'wiki',
  wikipedia: 'wiki',
  workbook: 'wiki',
  account: 'define',
  assertion: 'define',
  assumption: 'define',
  axiom: 'define',
  conjecture: 'define',
  connotation: 'define',
  definition: 'define',
  denotation: 'define',
  description: 'define',
  doctrine: 'define',
  dogma: 'define',
  explanation: 'define',
  hypothesis: 'define',
  interpretation: 'define',
  meaning: 'define',
  postulate: 'define',
  premise: 'define',
  presumption: 'define',
  principle: 'define',
  proposition: 'define',
  sense: 'define',
  signification: 'define',
  speculation: 'define',
  statement: 'define',
  supposition: 'define',
  tenet: 'define',
  theory: 'define',
  thesis: 'define',
  affiliated: 'synonym',
  akin: 'synonym',
  aligned: 'synonym',
  alike: 'synonym',
  allied: 'synonym',
  amalgamated: 'synonym',
  analogous: 'synonym',
  associated: 'synonym',
  blended: 'synonym',
  bound: 'synonym',
  combined: 'synonym',
  comparable: 'synonym',
  connected: 'synonym',
  consolidated: 'synonym',
  corresponding: 'synonym',
  equivalent: 'synonym',
  fused: 'synonym',
  harmonized: 'synonym',
  integrated: 'synonym',
  linked: 'synonym',
  matching: 'synonym',
  merged: 'synonym',
  parallel: 'synonym',
  reconciled: 'synonym',
  similar: 'synonym',
  synonyms: 'synonym',
  synthesized: 'synonym',
  tied: 'synonym',
  unified: 'synonym',
  antithesis: 'antonym',
  antonyms: 'antonym',
  clash: 'antonym',
  collision: 'antonym',
  conflict: 'antonym',
  contradiction: 'antonym',
  contrary: 'antonym',
  counter: 'antonym',
  counterargument: 'antonym',
  coup: 'antonym',
  defiance: 'antonym',
  denial: 'antonym',
  disagreement: 'antonym',
  dispute: 'antonym',
  dissent: 'antonym',
  insurrection: 'antonym',
  inverse: 'antonym',
  mutiny: 'antonym',
  negation: 'antonym',
  objection: 'antonym',
  opposite: 'antonym',
  opposition: 'antonym',
  protest: 'antonym',
  rebellion: 'antonym',
  rebuttal: 'antonym',
  refutation: 'antonym',
  resistance: 'antonym',
  reverse: 'antonym',
  revolt: 'antonym',
  actuality: 'fact',
  allegiance: 'fact',
  assurance: 'fact',
  certainty: 'fact',
  certitude: 'fact',
  commitment: 'fact',
  confidence: 'fact',
  dedication: 'fact',
  devotion: 'fact',
  esteem: 'fact',
  facts: 'fact',
  faithfulness: 'fact',
  fealty: 'fact',
  fidelity: 'fact',
  guarantee: 'fact',
  homage: 'fact',
  loyalty: 'fact',
  oath: 'fact',
  pledge: 'fact',
  promise: 'fact',
  reality: 'fact',
  regard: 'fact',
  surety: 'fact',
  tribute: 'fact',
  truth: 'fact',
  verity: 'fact',
  vow: 'fact',
  warranty: 'fact',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Health & Fitness ───────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  action: 'workout',
  activity: 'workout',
  athletics: 'workout',
  bend: 'workout',
  burden: 'workout',
  effort: 'workout',
  exercise: 'workout',
  exertion: 'workout',
  fitness: 'workout',
  flex: 'workout',
  gym: 'workout',
  load: 'workout',
  motion: 'workout',
  movement: 'workout',
  physical: 'workout',
  pivot: 'workout',
  pressure: 'workout',
  rotate: 'workout',
  spin: 'workout',
  sport: 'workout',
  strain: 'workout',
  stress: 'workout',
  stretch: 'workout',
  swivel: 'workout',
  tension: 'workout',
  training: 'workout',
  turn: 'workout',
  twist: 'workout',
  weight: 'workout',
  whirl: 'workout',
   collation: 'diet',
  aliment: 'diet',
  banquet: 'diet',
  billoffare: 'diet',
  board: 'diet',
  buffet: 'diet',
  carte: 'diet',
  commons: 'diet',
  cooking: 'diet',
  cuisine: 'diet',
  culinary: 'diet',
  eating: 'diet',
  fare: 'diet',
  feast: 'diet',
  food: 'diet',
  gastronomy: 'diet',
  meal: 'diet',
  menu: 'diet',
  nourishment: 'diet',
  nutrition: 'diet',
  provisions: 'diet',
  rations: 'diet',
  recipe: 'diet',
  refection: 'diet',
  repast: 'diet',
  snack: 'diet',
  sustenance: 'diet',
  table: 'diet',
  victuals: 'diet',
  abyss: 'sleep',
  chasm: 'sleep',
  coma: 'sleep',
  doldrums: 'sleep',
  dormancy: 'sleep',
  doze: 'sleep',
  emptiness: 'sleep',
  hibernate: 'sleep',
  indolence: 'sleep',
  inertia: 'sleep',
  insensibility: 'sleep',
  lassitude: 'sleep',
  lethargy: 'sleep',
  listlessness: 'sleep',
  nap: 'sleep',
  nothingness: 'sleep',
  oblivion: 'sleep',
  relax: 'sleep',
  repose: 'sleep',
  rest: 'sleep',
  siesta: 'sleep',
  sloth: 'sleep',
  slumber: 'sleep',
  snooze: 'sleep',
  stagnation: 'sleep',
  stupor: 'sleep',
  torpor: 'sleep',
  unconsciousness: 'sleep',
  vacuum: 'sleep',
  void: 'sleep',
  calm: 'meditate',
  constraint: 'meditate',
  control: 'meditate',
  domination: 'meditate',
  dumbness: 'meditate',
  hush: 'meditate',
  inhibition: 'meditate',
  mastery: 'meditate',
  meditation: 'meditate',
  mindfulness: 'meditate',
  muteness: 'meditate',
  oppression: 'meditate',
  peace: 'meditate',
  quiet: 'meditate',
  repression: 'meditate',
  restraint: 'meditate',
  reticence: 'meditate',
  serenity: 'meditate',
  silence: 'meditate',
  speechlessness: 'meditate',
  stillness: 'meditate',
  subjugation: 'meditate',
  suppression: 'meditate',
  taciturnity: 'meditate',
  tranquility: 'meditate',
  voicelessness: 'meditate',
  wordlessness: 'meditate',
  yoga: 'meditate',
  zen: 'meditate',
  allay: 'hydrate',
  alleviate: 'hydrate',
  appease: 'hydrate',
  assuage: 'hydrate',
  balance: 'hydrate',
  beverage: 'hydrate',
  comfort: 'hydrate',
  conciliate: 'hydrate',
  drink: 'hydrate',
  ease: 'hydrate',
  fluid: 'hydrate',
  harmonize: 'hydrate',
  liquid: 'hydrate',
  mitigate: 'hydrate',
  mollify: 'hydrate',
  pacify: 'hydrate',
  placate: 'hydrate',
  propitiate: 'hydrate',
  quench: 'hydrate',
  reconcile: 'hydrate',
  refreshment: 'hydrate',
  relieve: 'hydrate',
  sate: 'hydrate',
  satiate: 'hydrate',
  satisfy: 'hydrate',
  slake: 'hydrate',
  soothe: 'hydrate',
  water: 'hydrate',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Travel & Geography ─────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  angle: 'map',
  aspect: 'map',
  atlas: 'map',
  delineation: 'map',
  depiction: 'map',
  drawing: 'map',
  facet: 'map',
  globe: 'map',
  image: 'map',
  maps: 'map',
  outlook: 'map',
  painting: 'map',
  panorama: 'map',
  perspective: 'map',
  photograph: 'map',
  picture: 'map',
  plan: 'map',
  portrayal: 'map',
  prospect: 'map',
  rendering: 'map',
  scene: 'map',
  snapshot: 'map',
  view: 'map',
  vista: 'map',
  aisle: 'directions',
  alley: 'directions',
  avenue: 'directions',
  boulevard: 'directions',
  corridor: 'directions',
  course: 'directions',
  drive: 'directions',
  expressway: 'directions',
  footpath: 'directions',
  freeway: 'directions',
  gangway: 'directions',
  hallway: 'directions',
  highway: 'directions',
  lane: 'directions',
  motorway: 'directions',
  parkway: 'directions',
  passage: 'directions',
  passageway: 'directions',
  path: 'directions',
  pavement: 'directions',
  road: 'directions',
  route: 'directions',
  sidewalk: 'directions',
  street: 'directions',
  tollway: 'directions',
  track: 'directions',
  trail: 'directions',
  turnpike: 'directions',
  walkway: 'directions',
  way: 'directions',
   infosphere: 'flight',
  aeroplane: 'flight',
  air: 'flight',
  aircraft: 'flight',
  airline: 'flight',
  airplane: 'flight',
  anthroposphere: 'flight',
  atmosphere: 'flight',
  aviation: 'flight',
  biosphere: 'flight',
  blogosphere: 'flight',
  cryosphere: 'flight',
  exosphere: 'flight',
  firmament: 'flight',
  fly: 'flight',
  heavens: 'flight',
  hydrosphere: 'flight',
  ionosphere: 'flight',
  jet: 'flight',
  lithosphere: 'flight',
  magnetosphere: 'flight',
  mesosphere: 'flight',
  noosphere: 'flight',
  pedosphere: 'flight',
  plane: 'flight',
  sky: 'flight',
  stratosphere: 'flight',
  technosphere: 'flight',
  thermosphere: 'flight',
  troposphere: 'flight',
  accommodation: 'hotel',
  anchorage: 'hotel',
  asylum: 'hotel',
  berth: 'hotel',
  breakwater: 'hotel',
  dam: 'hotel',
  dock: 'hotel',
  embankment: 'hotel',
  harbor: 'hotel',
  haven: 'hotel',
  hostel: 'hotel',
  housing: 'hotel',
  inn: 'hotel',
  jetty: 'hotel',
  landing: 'hotel',
  levee: 'hotel',
  lodge: 'hotel',
  lodging: 'hotel',
  mooring: 'hotel',
  motel: 'hotel',
  pier: 'hotel',
  port: 'hotel',
  quay: 'hotel',
  refuge: 'hotel',
  resort: 'hotel',
  retreat: 'hotel',
  sanctuary: 'hotel',
  seawall: 'hotel',
  shelter: 'hotel',
  wharf: 'hotel',
  asset: 'currency',
  barter: 'currency',
  belonging: 'currency',
  business: 'currency',
  commerce: 'currency',
  commodity: 'currency',
  conversion: 'currency',
  convert: 'currency',
  estate: 'currency',
  forex: 'currency',
  fx: 'currency',
  goods: 'currency',
  holding: 'currency',
  mercantile: 'currency',
  merchandise: 'currency',
  possession: 'currency',
  product: 'currency',
  property: 'currency',
  provision: 'currency',
  resource: 'currency',
  stock: 'currency',
  supply: 'currency',
  swap: 'currency',
  wares: 'currency',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Food & Cooking ─────────────────────────────────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  bake: 'recipe',
  blanch: 'recipe',
  boil: 'recipe',
  bottle: 'recipe',
  braise: 'recipe',
  brine: 'recipe',
  can: 'recipe',
  caramelize: 'recipe',
  cook: 'recipe',
  cure: 'recipe',
  ferment: 'recipe',
  fry: 'recipe',
  glaze: 'recipe',
  grill: 'recipe',
  jar: 'recipe',
  marinate: 'recipe',
  parboil: 'recipe',
  pickle: 'recipe',
  poach: 'recipe',
  recipes: 'recipe',
  saute: 'recipe',
  scald: 'recipe',
  sear: 'recipe',
  simmer: 'recipe',
  smoke: 'recipe',
  stew: 'recipe',
  allocation: 'ingredient',
  allotment: 'ingredient',
  amount: 'ingredient',
  apportionment: 'ingredient',
  component: 'ingredient',
  constituent: 'ingredient',
  division: 'ingredient',
  dosage: 'ingredient',
  dose: 'ingredient',
  duration: 'ingredient',
  element: 'ingredient',
  factor: 'ingredient',
  ingredients: 'ingredient',
  item: 'ingredient',
  length: 'ingredient',
  mass: 'ingredient',
  measure: 'ingredient',
  module: 'ingredient',
  part: 'ingredient',
  piece: 'ingredient',
  portion: 'ingredient',
  quantity: 'ingredient',
  quota: 'ingredient',
  ration: 'ingredient',
  section: 'ingredient',
  segment: 'ingredient',
  unit: 'ingredient',
  bistro: 'restaurant',
  brasserie: 'restaurant',
  cabaret: 'restaurant',
  cafe: 'restaurant',
  casino: 'restaurant',
  club: 'restaurant',
  diner: 'restaurant',
  discotheque: 'restaurant',
  dive: 'restaurant',
  eatery: 'restaurant',
  farmtotable: 'restaurant',
  fivestar: 'restaurant',
  fusion: 'restaurant',
  gourmet: 'restaurant',
  greasyspoon: 'restaurant',
  hangout: 'restaurant',
  hautecuisine: 'restaurant',
  holeinthewall: 'restaurant',
  joint: 'restaurant',
  lounge: 'restaurant',
  michelin: 'restaurant',
  nightclub: 'restaurant',
  pub: 'restaurant',
  restaurants: 'restaurant',
  saloon: 'restaurant',
  speakeasy: 'restaurant',
  tavern: 'restaurant',
  trattoria: 'restaurant',
  wateringhole: 'restaurant',
  amusement: 'reviewfood',
  appreciate: 'reviewfood',
  avocation: 'reviewfood',
  contentment: 'reviewfood',
  degustation: 'reviewfood',
  delight: 'reviewfood',
  diversion: 'reviewfood',
  enjoy: 'reviewfood',
  enjoyment: 'reviewfood',
  entertainment: 'reviewfood',
  flavor: 'reviewfood',
  foodreview: 'reviewfood',
  fulfillment: 'reviewfood',
  gratification: 'reviewfood',
  gustation: 'reviewfood',
  hobby: 'reviewfood',
  interest: 'reviewfood',
  palate: 'reviewfood',
  pastime: 'reviewfood',
  pleasure: 'reviewfood',
  pursuit: 'reviewfood',
  recreation: 'reviewfood',
  relish: 'reviewfood',
  satisfaction: 'reviewfood',
  savor: 'reviewfood',
  sideline: 'reviewfood',
  taste: 'reviewfood',
  tastetest: 'reviewfood',
  tasting: 'reviewfood',
  vocation: 'reviewfood',
  calories: 'nutrition',
  carbs: 'nutrition',
  defense: 'nutrition',
  diet: 'nutrition',
  durability: 'nutrition',
  endurance: 'nutrition',
  energy: 'nutrition',
  fats: 'nutrition',
  force: 'nutrition',
  hardiness: 'nutrition',
  health: 'nutrition',
  immunity: 'nutrition',
  longevity: 'nutrition',
  might: 'nutrition',
  minerals: 'nutrition',
  nutrients: 'nutrition',
  power: 'nutrition',
  protection: 'nutrition',
  protein: 'nutrition',
  resilience: 'nutrition',
  robustness: 'nutrition',
  stamina: 'nutrition',
  strength: 'nutrition',
  toughness: 'nutrition',
  vigor: 'nutrition',
  vitality: 'nutrition',
  vitamins: 'nutrition',
  wellness: 'nutrition',
};

// ─── Subcommand Aliases ─────────────────────────────────────────────────────

export const subcommandAliases = {
  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Generic (50 aliases) ─────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  l: 'list',
  ls: 'list',
  all: 'list',
  everything: 'list',
  full: 'list',
  complete: 'list',
  total: 'list',
  s: 'set',
  set: 'set',
  update: 'set',
  edit: 'set',
  modify: 'set',
  change: 'set',
  adjust: 'set',
  configure: 'set',
  i: 'info',
  details: 'info',
  view: 'info',
  show: 'info',
  display: 'info',
  inspect: 'info',
  examine: 'info',
  r: 'remove',
  rm: 'remove',
  del: 'remove',
  delete: 'remove',
  erase: 'remove',
  purge: 'remove',
  n: 'next',
  nxt: 'next',
  upcoming: 'next',
  following: 'next',
  sc: 'setchannel',
  setchannel: 'setchannel',
  channel: 'setchannel',
  ch: 'setchannel',
  setrole: 'setrole',
  sr: 'setrole',
  role: 'setrole',
  enable: 'enable',
  on: 'enable',
  activate: 'enable',
  start: 'enable',
  disable: 'disable',
  off: 'disable',
  deactivate: 'disable',
  stop: 'disable',
  reset: 'reset',
  default: 'reset',
  clear: 'reset',
  wipe: 'reset',
  toggle: 'toggle',
  t: 'toggle',
  switch: 'toggle',
  flip: 'toggle',
  create: 'create',
  new: 'create',
  make: 'create',
  build: 'create',
  generate: 'create',
  add: 'add',
  a: 'add',
  insert: 'add',
  append: 'add',
  attach: 'add',
  remove: 'remove',
  rm: 'remove',
  detach: 'remove',
  clear: 'clear',
  clean: 'clear',
  empty: 'clear',
  config: 'config',
  cfg: 'config',
  settings: 'config',
  preferences: 'config',
  options: 'config',
  setup: 'setup',
  init: 'setup',
  initialize: 'setup',
  install: 'setup',
  test: 'test',
  preview: 'test',
  demo: 'test',
  try: 'test',
  export: 'export',
  save: 'export',
  backup: 'export',
  import: 'import',
  load: 'import',
  restore: 'restore',
  recover: 'restore',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Todo (15 aliases) ────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  a: 'add',
  c: 'complete',
  done: 'complete',
  finish: 'complete',
  d: 'complete',
  check: 'complete',
  mark: 'complete',
  tick: 'complete',
  uncheck: 'uncheck',
  unmark: 'uncheck',
  untick: 'uncheck',
  prioritize: 'prioritize',
  urgent: 'prioritize',
  important: 'prioritize',
  star: 'prioritize',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Giveaway (20 aliases) ────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  start: 'create',
  begin: 'create',
  launch: 'create',
  initiate: 'create',
  stop: 'end',
  finish: 'end',
  terminate: 'end',
  conclude: 'end',
  roll: 'reroll',
  reroll: 'reroll',
  redraw: 'reroll',
  retry: 'reroll',
  entries: 'entries',
  participants: 'entries',
  contestants: 'entries',
  requirements: 'requirements',
  reqs: 'requirements',
  conditions: 'requirements',
  prize: 'prize',
  reward: 'prize',
  winners: 'winners',
  victors: 'winners',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Reaction Roles (15 aliases) ──────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  add: 'add',
  create: 'add',
  make: 'add',
  remove: 'remove',
  delete: 'remove',
  destroy: 'remove',
  list: 'list',
  view: 'list',
  show: 'list',
  edit: 'edit',
  update: 'edit',
  modify: 'edit',
  type: 'type',
  style: 'type',
  mode: 'type',
  unique: 'unique',
  exclusive: 'unique',
  max: 'max',
  maximum: 'max',
  min: 'min',
  minimum: 'min',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Auto-Moderation (40 aliases) ─────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  enable: 'enable',
  on: 'enable',
  activate: 'enable',
  start: 'enable',
  disable: 'disable',
  off: 'disable',
  deactivate: 'disable',
  stop: 'disable',
  config: 'configure',
  cfg: 'configure',
  settings: 'configure',
  configure: 'configure',
  setup: 'configure',
  logs: 'logs',
  logchannel: 'logs',
  log: 'logs',
  whitelist: 'whitelist',
  wl: 'whitelist',
  allow: 'whitelist',
  permit: 'whitelist',
  blacklist: 'blacklist',
  bl: 'blacklist',
  block: 'blacklist',
  deny: 'blacklist',
  threshold: 'threshold',
  limit: 'threshold',
  max: 'threshold',
  cap: 'threshold',
  action: 'action',
  punish: 'action',
  punishment: 'action',
  consequence: 'action',
  exempt: 'exempt',
  ignore: 'exempt',
  bypass: 'exempt',
  skip: 'exempt',
  exemptrole: 'exemptrole',
  exemptchannel: 'exemptchannel',
  duration: 'duration',
  time: 'duration',
  length: 'duration',
  cooldown: 'cooldown',
  cd: 'cooldown',
  delay: 'cooldown',
  notify: 'notify',
  dm: 'notify',
  message: 'message',
  msg: 'message',
  reason: 'reason',
  custommsg: 'custommsg',
  custommessage: 'custommsg',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Music Subcommands (50 aliases) ─────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  now: 'now',
  current: 'now',
  next: 'next',
  nxt: 'next',
  prev: 'prev',
  previous: 'prev',
  last: 'prev',
  loopone: 'loopone',
  loopall: 'loopall',
  loopoff: 'loopoff',
  loopqueue: 'loopqueue',
  looptrack: 'looptrack',
  clearqueue: 'clearqueue',
  cq: 'clearqueue',
  empty: 'clearqueue',
  remove: 'remove',
  deq: 'remove',
  delete: 'remove',
  skipto: 'skipto',
  jumpto: 'skipto',
  gototrack: 'skipto',
  moveto: 'moveto',
  swap: 'swap',
  exchange: 'swap',
  replay: 'replay',
  restart: 'restart',
  lyrics: 'lyrics',
  words: 'lyrics',
  related: 'related',
  similar: 'related',
  recommended: 'related',
  filter: 'filter',
  eq: 'filter',
  equalizer: 'filter',
  bass: 'bass',
  lowend: 'bass',
  treble: 'treble',
  highend: 'treble',
  karaoke: 'karaoke',
  tremolo: 'tremolo',
  vibrato: 'vibrato',
  earrape: 'earrape',
  superslow: 'superslow',
  superspeed: 'superspeed',
  reverse: 'reverse',
  backwards: 'reverse',
  '8d': '8d',
  '3d': '3d',
  surround: '8d',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Leveling Subcommands (20 aliases) ────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  setchannel: 'setchannel',
  setmessage: 'setmessage',
  setimage: 'setimage',
  setcolor: 'setcolor',
  setbg: 'setbg',
  setbackground: 'setbg',
  doublexp: 'doublexp',
  weekendxp: 'weekendxp',
  noxprole: 'noxprole',
  resetuser: 'resetuser',
  resetall: 'resetall',
  reseteveryone: 'resetall',
  import: 'import',
  export: 'export',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Welcome Subcommands (15 aliases) ─────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  setchannel: 'setchannel',
  setmessage: 'setmessage',
  setimage: 'setimage',
  setcolor: 'setcolor',
  setfooter: 'setfooter',
  setdm: 'setdm',
  test: 'test',
  preview: 'test',
  reset: 'reset',
  default: 'reset',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Ticket Subcommands (20 aliases) ──────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  open: 'open',
  reopen: 'reopen',
  close: 'close',
  claim: 'claim',
  unclaim: 'unclaim',
  assign: 'assign',
  priority: 'priority',
  note: 'note',
  transcript: 'transcript',
  archive: 'archive',
  category: 'category',
  panel: 'panel',
  button: 'button',
  modal: 'modal',
  form: 'modal',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Moderation Subcommands (30 aliases) ──────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  history: 'history',
  modstats: 'modstats',
  duration: 'duration',
  extend: 'extend',
  reduce: 'reduce',
  shorten: 'reduce',
  reason: 'reason',
  edit: 'edit',
  appeal: 'appeal',
  revoke: 'revoke',
  softban: 'softban',
  tempban: 'tempban',
  massban: 'massban',
  masskick: 'masskick',
  massmute: 'massmute',
  voicemute: 'voicemute',
  voicekick: 'voicekick',
  move: 'move',
  drag: 'move',
  deafen: 'deafen',
  undeafen: 'undeafen',
  disconnect: 'disconnect',
  dc: 'disconnect',
  kickvoice: 'voicekick',
  mutevoice: 'voicemute',

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── Economy Subcommands (50 aliases) ─────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════
  work: 'work',
  crime: 'crime',
  slut: 'slut',
  whore: 'slut',
  rob: 'rob',
  steal: 'rob',
  deposit: 'deposit',
  withdraw: 'withdraw',
  give: 'give',
  share: 'share',
  donate: 'give',
  slots: 'slots',
  roulette: 'roulette',
  blackjack: 'blackjack',
  bj: 'blackjack',
  coinflip: 'coinflip',
  cf: 'coinflip',
  horse: 'horse',
  bet: 'bet',
  wager: 'bet',
  lottery: 'lottery',
  lotto: 'lottery',
  scratch: 'scratch',
  invest: 'invest',
  stock: 'stock',
  crypto: 'crypto',
  bitcoin: 'bitcoin',
  btc: 'bitcoin',
  pet: 'pet',
  petbuy: 'petbuy',
  petfeed: 'petfeed',
  pettrain: 'pettrain',
  petfight: 'petfight',
  petlist: 'petlist',
  marry: 'marry',
  divorce: 'divorce',
  family: 'family',
  adopt: 'adopt',
  disown: 'disown',
  shop: 'shop',
  buy: 'buy',
  sell: 'sell',
  use: 'use',
  inventory: 'inventory',
  inv: 'inventory',
  craft: 'craft',
  recipe: 'recipe',
  leaderboard: 'leaderboard',
  lb: 'leaderboard',
  rich: 'rich',
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
  vote: 'vote',
  streak: 'streak',
  achievements: 'achievements',
  badges: 'badges',
  title: 'title',
  titles: 'titles',
  background: 'background',
  card: 'card',
  customize: 'customize',
  reset: 'reset',
  prestige: 'prestige',
  rebirth: 'prestige',
  loan: 'loan',
  bankrob: 'bankrob',
  heist: 'heist',
  bounty: 'bounty',
  contract: 'contract',
  hit: 'hit',
  job: 'job',
  jobs: 'jobs',
  apply: 'apply',
  resign: 'resign',
  promote: 'promote',
  demote: 'demote',
  company: 'company',
  business: 'company',
  shopcreate: 'shopcreate',
  shopedit: 'shopedit',
  shopdelete: 'shopdelete',
  auction: 'auction',
  bid: 'bid',
  trade: 'trade',
  market: 'market',
  fish: 'fish',
  hunt: 'hunt',
  dig: 'dig',
  chop: 'chop',
  mine: 'mine',
  explore: 'explore',
  adventure: 'adventure',
  quest: 'quest',
  dungeon: 'dungeon',
  raid: 'raid',
  boss: 'boss',
  battle: 'battle',
  training: 'training',
  train: 'train',
  levelup: 'levelup',
  skill: 'skill',
  skills: 'skills',
  skilltree: 'skilltree',
  upgrade: 'upgrade',
  enchant: 'enchant',
  forge: 'forge',
  repair: 'repair',
  durability: 'durability',
  stats: 'stats',
  profile: 'profile',
  settings: 'settings',
  config: 'config',
};

// ─── Auto-Moderation Rule Aliases ─────────────────────────────────────────────

export const automodRuleAliases = {
  // Spam detection
  spam: 'antiSpam',
  'anti-spam': 'antiSpam',
  flood: 'antiSpam',
  flooding: 'antiSpam',
  repetition: 'antiSpam',
  repeat: 'antiSpam',
  copypaste: 'antiSpam',
  chain: 'antiSpam',
  copypasta: 'antiSpam',
  walls: 'antiSpam',

  // Raid protection
  raid: 'antiRaid',
  'anti-raid': 'antiRaid',
  'mass-join': 'antiRaid',
  joinstorm: 'antiRaid',
  joinflood: 'antiRaid',
  botraid: 'antiRaid',
  altraid: 'antiRaid',
  nuke: 'antiRaid',
  'member-flood': 'antiRaid',
  'join-raid': 'antiRaid',

  // Caps lock
  caps: 'antiCaps',
  'all-caps': 'antiCaps',
  uppercase: 'antiCaps',
  'caps-lock': 'antiCaps',
  screaming: 'antiCaps',
  yell: 'antiCaps',
  shouting: 'antiCaps',
  'big-letters': 'antiCaps',

  // Invite links
  invites: 'antiInvite',
  'discord-invites': 'antiInvite',
  'server-ads': 'antiInvite',
  'guild-invites': 'antiInvite',
  inviteads: 'antiInvite',
  selfpromo: 'antiInvite',
  externalinvite: 'antiInvite',
  'invite-link': 'antiInvite',
  'server-link': 'antiInvite',

  // External links
  links: 'antiLink',
  urls: 'antiLink',
  'external-links': 'antiLink',
  phishing: 'antiLink',
  scamlinks: 'antiLink',
  malware: 'antiLink',
  ipgrabber: 'antiLink',
  suspicious: 'antiLink',
  'bad-link': 'antiLink',
  'dangerous-link': 'antiLink',

  // Mentions
  mentions: 'mentionSpam',
  'mass-mentions': 'mentionSpam',
  'everyone-spam': 'mentionSpam',
  'here-spam': 'mentionSpam',
  pingspam: 'mentionSpam',
  mentionabuse: 'mentionSpam',
  roleping: 'mentionSpam',
  'mention-flood': 'mentionSpam',
  'ping-spam': 'mentionSpam',

  // NSFW / inappropriate
  nsfw: 'antiNsfw',
  inappropriate: 'antiNsfw',
  lewd: 'antiNsfw',
  porn: 'antiNsfw',
  hentai: 'antiNsfw',
  sexual: 'antiNsfw',
  gore: 'antiNsfw',
  violence: 'antiNsfw',
  'adult-content': 'antiNsfw',
  'explicit-content': 'antiNsfw',

  // Zalgo / unicode abuse
  zalgo: 'antiZalgo',
  unicode: 'antiZalgo',
  'special-chars': 'antiZalgo',
  diacritics: 'antiZalgo',
  glitchtext: 'antiZalgo',
  cursed: 'antiZalgo',
  weirdtext: 'antiZalgo',
  'fancy-text': 'antiZalgo',
  'crazy-text': 'antiZalgo',

  // Profanity / bad words
  profanity: 'antiProfanity',
  swear: 'antiProfanity',
  slurs: 'antiProfanity',
  badwords: 'antiProfanity',
  cursing: 'antiProfanity',
  language: 'antiProfanity',
  toxicity: 'antiProfanity',
  insult: 'antiProfanity',
  'bad-language': 'antiProfanity',
  'foul-language': 'antiProfanity',

  // Self-bot / ghost pings
  selfbot: 'antiSelfbot',
  ghostping: 'antiGhostPing',
  'ghost-ping': 'antiGhostPing',
  pingdelete: 'antiGhostPing',
  'ghost-mention': 'antiGhostPing',
  'deleted-ping': 'antiGhostPing',

  // Dehoist / nickname abuse
  dehoist: 'antiDehoist',
  hoisting: 'antiDehoist',
  'z-name': 'antiDehoist',
  symbolname: 'antiDehoist',
  'special-name': 'antiDehoist',
  'weird-name': 'antiDehoist',

  // Emoji spam
  emojispam: 'antiEmojiSpam',
  'emoji-spam': 'antiEmojiSpam',
  emoteflood: 'antiEmojiSpam',
  'emoji-abuse': 'antiEmojiSpam',
  'too-many-emojis': 'antiEmojiSpam',
  'emoji-flood': 'antiEmojiSpam',

  // Newline / wall spam
  newline: 'antiNewline',
  'newline-spam': 'antiNewline',
  walltext: 'antiNewline',
  'wall-of-text': 'antiNewline',
  enterspam: 'antiNewline',
  'line-spam': 'antiNewline',
  'enter-flood': 'antiNewline',

  // Sticker / GIF spam
  sticker: 'antiStickerSpam',
  'sticker-spam': 'antiStickerSpam',
  gifspam: 'antiGifSpam',
  'gif-spam': 'antiGifSpam',
  imageflood: 'antiImageFlood',
  'image-spam': 'antiImageFlood',
  'media-spam': 'antiImageFlood',
  'attachment-spam': 'antiImageFlood',

  // Spam bots / webhook spam
  webhookspam: 'antiWebhookSpam',
  'webhook-spam': 'antiWebhookSpam',
  botspam: 'antiBotSpam',
  'bot-spam': 'antiBotSpam',
  tokenleak: 'antiTokenLeak',
  'token-leak': 'antiTokenLeak',
  'api-key-leak': 'antiTokenLeak',
  'secret-leak': 'antiTokenLeak',

  // Doxxing protection
  doxxing: 'antiDoxxing',
  'doxx-protection': 'antiDoxxing',
  'personal-info': 'antiDoxxing',
  'private-info': 'antiDoxxing',
  'info-leak': 'antiDoxxing',
  'data-leak': 'antiDoxxing',
  'address-leak': 'antiDoxxing',
  'phone-leak': 'antiDoxxing',
  'email-leak': 'antiDoxxing',
};

// ─── Auto-Moderation Action Aliases ─────────────────────────────────────────

export const automodActionAliases = {
  none: 'none',
  off: 'none',
  disable: 'none',
  nothing: 'none',
  ignore: 'none',
  skip: 'none',
  bypass: 'none',

  log: 'logOnly',
  'log-only': 'logOnly',
  record: 'logOnly',
  audit: 'logOnly',
  monitor: 'logOnly',
  track: 'logOnly',
  observe: 'logOnly',
  watch: 'logOnly',

  warn: 'warnUser',
  'warn-user': 'warnUser',
  alert: 'warnUser',
  caution: 'warnUser',
  notify: 'warnUser',
  dm: 'warnUser',
  message: 'warnUser',
  'send-warning': 'warnUser',

  delete: 'deleteMessage',
  'delete-msg': 'deleteMessage',
  remove: 'deleteMessage',
  del: 'deleteMessage',
  purge: 'deleteMessage',
  erase: 'deleteMessage',
  'remove-msg': 'deleteMessage',
  'clear-msg': 'deleteMessage',

  'warn-delete': 'warnAndDelete',
  'delete-warn': 'warnAndDelete',
  'warn-del': 'warnAndDelete',
  'del-warn': 'warnAndDelete',
  'alert-delete': 'warnAndDelete',
  'delete-alert': 'warnAndDelete',

  mute: 'timeoutUser',
  'timeout-user': 'timeoutUser',
  'temp-mute': 'timeoutUser',
  silence: 'timeoutUser',
  restrict: 'timeoutUser',
  quarantine: 'timeoutUser',
  shadowban: 'timeoutUser',
  'put-in-timeout': 'timeoutUser',
  'corner-time': 'timeoutUser',

  kick: 'kickUser',
  'kick-user': 'kickUser',
  remove: 'kickUser',
  eject: 'kickUser',
  boot: 'kickUser',
  'remove-user': 'kickUser',
  'boot-user': 'kickUser',

  ban: 'banUser',
  'ban-user': 'banUser',
  permaban: 'banUser',
  hackban: 'banUser',
  'force-ban': 'banUser',
  'id-ban': 'banUser',
  'permanent-ban': 'banUser',
  'hard-ban': 'banUser',

  softban: 'softbanUser',
  'soft-ban': 'softbanUser',
  'temp-ban': 'tempbanUser',
  tempban: 'tempbanUser',
  'short-ban': 'softbanUser',
  'temporary-ban': 'tempbanUser',
  'timed-ban': 'tempbanUser',

  strikemute: 'strikeMute',
  'strike-mute': 'strikeMute',
  'warn-mute': 'strikeMute',
  '3-strike': 'strikeMute',
  '3-warn': 'strikeMute',
  'three-strike': 'strikeMute',
  'three-warn': 'strikeMute',

  strikeban: 'strikeBan',
  'strike-ban': 'strikeBan',
  '3-strike-ban': 'strikeBan',
  '3-warn-ban': 'strikeBan',
  'three-strike-ban': 'strikeBan',
  'three-warn-ban': 'strikeBan',
};

// ─── Resolve Functions ───────────────────────────────────────────────────────

/**
 * Resolve a command alias to its full command name
 * @param {string} commandName - The command name (could be an alias)
 * @returns {string} - The full command name, or the original if not an alias
 */
export function resolveCommandAlias(commandName) {
  if (!commandName || typeof commandName !== 'string') {
    return commandName;
  }
  const normalized = commandName.trim().toLowerCase().substring(0, MAX_ALIAS_LENGTH);
  return commandAliases[normalized] || normalized;
}

/**
 * Resolve a subcommand alias to its full subcommand name
 * @param {string} subcommandName - The subcommand name (could be an alias)
 * @returns {string} - The full subcommand name, or the original if not an alias
 */
export function resolveSubcommandAlias(subcommandName) {
  if (!subcommandName || typeof subcommandName !== 'string') {
    return subcommandName;
  }
  const normalized = subcommandName.trim().toLowerCase().substring(0, MAX_ALIAS_LENGTH);
  return subcommandAliases[normalized] || normalized;
}

/**
 * Resolve an auto-moderation rule alias
 * @param {string} ruleName
 * @returns {string}
 */
export function resolveAutomodRule(ruleName) {
  if (!ruleName || typeof ruleName !== 'string') {
    return ruleName;
  }
  const normalized = ruleName.trim().toLowerCase();
  return automodRuleAliases[normalized] || normalized;
}

/**
 * Resolve an auto-moderation action alias
 * @param {string} actionName
 * @returns {string}
 */
export function resolveAutomodAction(actionName) {
  if (!actionName || typeof actionName !== 'string') {
    return actionName;
  }
  const normalized = actionName.trim().toLowerCase();
  return automodActionAliases[normalized] || normalized;
}

// ─── Introspection ───────────────────────────────────────────────────────────

/**
 * Check if a command name is a known alias
 * @param {string} commandName
 * @returns {boolean}
 */
export function isCommandAlias(commandName) {
  if (!commandName || typeof commandName !== 'string') return false;
  return commandName.trim().toLowerCase() in commandAliases;
}

/**
 * Check if a subcommand name is a known alias
 * @param {string} subcommandName
 * @returns {boolean}
 */
export function isSubcommandAlias(subcommandName) {
  if (!subcommandName || typeof subcommandName !== 'string') return false;
  return subcommandName.trim().toLowerCase() in subcommandAliases;
}

/**
 * Check if an auto-moderation rule name is a known alias
 * @param {string} ruleName
 * @returns {boolean}
 */
export function isAutomodRuleAlias(ruleName) {
  if (!ruleName || typeof ruleName !== 'string') return false;
  return ruleName.trim().toLowerCase() in automodRuleAliases;
}

/**
 * Check if an auto-moderation action name is a known alias
 * @param {string} actionName
 * @returns {boolean}
 */
export function isAutomodActionAlias(actionName) {
  if (!actionName || typeof actionName !== 'string') return false;
  return actionName.trim().toLowerCase() in automodActionAliases;
}

/**
 * Get all aliases for a given command name
 * @param {string} fullCommandName
 * @returns {string[]} - Array of aliases (empty if none)
 */
export function getAliasesForCommand(fullCommandName) {
  const target = fullCommandName.toLowerCase();
  return Object.entries(commandAliases)
    .filter(([, full]) => full === target)
    .map(([alias]) => alias);
}

/**
 * Get all aliases for a given subcommand name
 * @param {string} fullSubcommandName
 * @returns {string[]}
 */
export function getAliasesForSubcommand(fullSubcommandName) {
  const target = fullSubcommandName.toLowerCase();
  return Object.entries(subcommandAliases)
    .filter(([, full]) => full === target)
    .map(([alias]) => alias);
}

/**
 * Get all aliases for a given auto-moderation rule
 * @param {string} fullRuleName
 * @returns {string[]}
 */
export function getAliasesForAutomodRule(fullRuleName) {
  const target = fullRuleName.toLowerCase();
  return Object.entries(automodRuleAliases)
    .filter(([, full]) => full === target)
    .map(([alias]) => alias);
}

/**
 * Get all aliases for a given auto-moderation action
 * @param {string} fullActionName
 * @returns {string[]}
 */
export function getAliasesForAutomodAction(fullActionName) {
  const target = fullActionName.toLowerCase();
  return Object.entries(automodActionAliases)
    .filter(([, full]) => full === target)
    .map(([alias]) => alias);
}

/**
 * Get all available auto-moderation rules
 * @returns {string[]}
 */
export function getAvailableAutomodRules() {
  return [...new Set(Object.values(automodRuleAliases))];
}

/**
 * Get all available auto-moderation actions
 * @returns {string[]}
 */
export function getAvailableAutomodActions() {
  return [...new Set(Object.values(automodActionAliases))];
}

/**
 * Get all available command names (unique full commands)
 * @returns {string[]}
 */
export function getAvailableCommands() {
  return [...new Set(Object.values(commandAliases))];
}

/**
 * Get all available subcommand names (unique full subcommands)
 * @returns {string[]}
 */
export function getAvailableSubcommands() {
  return [...new Set(Object.values(subcommandAliases))];
}

/**
 * Get total alias count statistics
 * @returns {{commands: number, subcommands: number, automodRules: number, automodActions: number, total: number}}
 */
export function getAliasStats() {
  return {
    commands: Object.keys(commandAliases).length,
    subcommands: Object.keys(subcommandAliases).length,
    automodRules: Object.keys(automodRuleAliases).length,
    automodActions: Object.keys(automodActionAliases).length,
    total: Object.keys(commandAliases).length + Object.keys(subcommandAliases).length + Object.keys(automodRuleAliases).length + Object.keys(automodActionAliases).length,
  };
}

// ─── Default Export ─────────────────────────────────────────────────────────

export default {
  commandAliases,
  subcommandAliases,
  automodRuleAliases,
  automodActionAliases,
  resolveCommandAlias,
  resolveSubcommandAlias,
  resolveAutomodRule,
  resolveAutomodAction,
  isCommandAlias,
  isSubcommandAlias,
  isAutomodRuleAlias,
  isAutomodActionAlias,
  getAliasesForCommand,
  getAliasesForSubcommand,
  getAliasesForAutomodRule,
  getAliasesForAutomodAction,
  getAvailableCommands,
  getAvailableSubcommands,
  getAvailableAutomodRules,
  getAvailableAutomodActions,
  getAliasStats,
};
